[project]
name = "hermes-inspector"
version = "0.0.1"
description = "UI visual inspection for Android, Apple, and Harmony devices(用于安卓,苹果,鸿蒙设备的UI可视化检查)"
authors = [
    {name = "tingxiuxiu", email = "112859811@qq.com"},
]
dependencies = [
    "fastapi[standard]>=0.127.0",
    "psutil>=7.1.3",
    "loguru>=0.7.3",
    "httpx>=0.28.1",
    "opencv-python>=4.12.0.88",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.scripts]
hermes-inspector = "hermes_inspector.main:main"

[tool.pdm.scripts]
dev.cmd = "python -m fastapi dev --host 0.0.0.0 --port 13710 src/hermes_inspector/main.py"

[tool.pyright]
pythonVersion = "3.14"
venvPath = ".venv"
pythonPath = ".venv/Scripts/python.exe"

[tool.pdm]
distribution = true

[[tool.pdm.source]]
name = "pypi"
url = "https://mirrors.huaweicloud.com/repository/pypi/simple"

[tool.pdm.build]
package-dir = "src"
includes = ["src/ta_inspector"]
excludes = ["./**/.git", "src/tests"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
